version: '3.8'
services:
  dbkampusku:
    image: postgres:latest
    volumes:
      - C:\Users\HUAWEI\Documents\base_project\kampusku:/var/run/postgresql/
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: dbkampusku
      POSTGRES_USER: dbkampusku
      POSTGRES_PASSWORD: rahasia

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - C:\Users\HUAWEI\Documents\base_project\zookeeper:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - C:\Users\HUAWEI\Documents\base_project\kafka-data:/var/run/docker.sock
    depends_on:
      - zookeeper

